#!/usr/bin/env php
<?php

/**
 * @package     SmartDrogariaSaude
 * @copyright   2023 SmartDrogariaSaude. All rights reserved.
 * @license     GNU GPL version 3; see LICENSE.txt
 * @link        https://smart-drogaria-saude.com
 */

// Register the auto-loader
require __DIR__ . '/bootstrap/autoload.php';

// Load the app
$app = require_once __DIR__ . '/bootstrap/app.php';

// Run the app
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
